### Get all User Requests

GET http://localhost:3000/api/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGNkZDhlNmJhMGQ1NzRmYTk3ODE1ZiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MzkyNzAxN30.aV6ik1GT990cKPEZ3SUfD922GYBEdClqtzLIfJAPZCE


###
POST http://localhost:3000/api/requests/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGI2NDdmN2M0NzkzOTcyM2EzMzljMCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MzY1NzE3OX0.JO0F_6Pr65-TXwGM3SHmkZ3eVOYTpiCvSV_Wxm_K7fA

{
    "title": "Admin Privileges",
}

###
POST http://localhost:3000/api/requests/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGNkZDhlNmJhMGQ1NzRmYTk3ODE1ZiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MzkyNzAxN30.aV6ik1GT990cKPEZ3SUfD922GYBEdClqtzLIfJAPZCE

{
    "title": "Password Reset",
    "passwordRequest": true

}

###

PUT http://localhost:3000/api/requests/6293d1d4d31c8e65aa25ba3f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGI2NDdmN2M0NzkzOTcyM2EzMzljMCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MzY1NzE3OX0.JO0F_6Pr65-TXwGM3SHmkZ3eVOYTpiCvSV_Wxm_K7fA

{}

###

DELETE http://localhost:3000/api/requests/6293d1d4d31c8e65aa25ba3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGI2NDdmN2M0NzkzOTcyM2EzMzljMCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MzY1NzE3OX0.JO0F_6Pr65-TXwGM3SHmkZ3eVOYTpiCvSV_Wxm_K7fA
