GET http://localhost:3000/api/orders

###
POST http://localhost:3000/api/order Content-Type: application/json

{
"title": "DHL", "price": 100, "info": "Postombud", "image": "URL", "expectedArrival": "2022-05-28"
}

###

PUT http://localhost:3000/api/order/62878f2ab155b83835486ad7 Content-Type: application/json

###
