### Get all orders

GET http://localhost:3000/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTc3NDQyYWQ4MjkzZTFkNGY0MmNlMyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1NDEwODkwNn0.ULYS-jdqDWov_cKnHI6UZnCXE5jGzLkNW1vo2cFR4pU


###Gets a specific order

GET http://localhost:3000/api/order/:id

###Gets a specific users orders

GET http://localhost:3000/api/order/user/628b647f7c47939723a339c0


### CREATE ORDER
POST http://localhost:3000/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTc3NDQyYWQ4MjkzZTFkNGY0MmNlMyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1NDEwODkwNn0.ULYS-jdqDWov_cKnHI6UZnCXE5jGzLkNW1vo2cFR4pU

{
  "userID": "628b647f7c47939723a339c0",
  "products": [{
    "title": "Leica M-10R svart 222",
    "price": 89900,
    "images": [
      "6290d221651a5fc114d7ad9c"
    ],
    "longInfo": "bla bla bla",
    "info": [
      "Info1",
      "Info2",
      "Info3"
    ],
    "category": [
      "628a970744f4a48145b62121"
    ]
  }],
  "deliveryAddress": {
  "street": "Torkelsgatan 4A",
  "zipcode": 41658,
  "city": "Göteborg",
  "firstName": "Maximilian",
  "lastName": "Widman",
  "phoneNumber": "0763198705"
  },
  "deliveryOption": {
    "title": "Postnord",
    "price": 79,
    "info": "Hemleverans",
    "expectedArrival": "2022-05-28T00:00:00.000Z",
    "image": "URL"
  }
}



###

PUT http://localhost:3000/api/order/62878f2ab155b83835486ad7
Content-Type: application/json


{
  "userID": "628b647f7c47939723a339c0",
  "products": [{
    "title": "Leica M-10R vit",
    "price": 89900,
    "images": [
      "6290d221651a5fc114d7ad9c"
    ],
    "longInfo": "bla bla bla",
    "info": [
      "Info1",
      "Info2",
      "Info3"
    ],
    "category": [
      "628a970744f4a48145b62121"
    ]
  }],
  "deliveryAddress": {
  "street": "Torkelsgatan 4A",
  "zipcode": 41658,
  "city": "Göteborg",
  "firstName": "Maximilian",
  "lastName": "Widman"
  },
  "deliveryMethod": {
    "title": "Postnord",
    "price": 79,
    "info": "Hemleverans",
    "expectedArrival": "2022-05-28T00:00:00.000Z",
    "image": "URL"
  }
}

###
