# Get all products
GET http://localhost:3000/api/products
###

# Get a single product
GET http://localhost:3000/api/products/628ce29b7cf6edafccd9c90e
###


GET http://localhost:3000/api/products/categories/628a970744f4a48145b62121
###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "Leica M-10R svart",
    "price": 89900,
    "images": ["628ce13b7cf6edafccd9c908"],
    "longInfo": "bla bla bla",
    "info": ["Info1", "Info2", "Info3"],
    "category": ["628a970744f4a48145b62121"],
    "createdAt": "{{$localDatetime iso8601}}",
    "updatedAt": "{{$localDatetime iso8601}}"
}
###

PUT http://localhost:3000/api/products/628b6da1f274ce912d496c40
Content-Type: application/json

{
    "user": "Erik",
    "title": "Kamera",
    "price": 20000,
    "images": "[image_url]",
    "longInfo": "bla bla bla",
    "info": ["Info1", "Info2", "Info3"],
    "category": "[Digital Kamera]",
    "createdAt": "{{$localDatetime iso8601}}",
    "updatedAt": "{{$localDatetime iso8601}}",
    "quantity": 1,
    "stock": 1
}
