GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/<userId>

###

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

PUT http://localhost:3000/api/user/password/<idOfUserToChangePassword>
Content-Type: application/json
Authorization: Bearer <Token you get from login>

{
    "oldPassword": "",
    "newPassword": ""
}

###

PUT http://localhost:3000/api/user/email/<idOfUserToChangeEmail>
Content-Type: application/json
Authorization: Bearer <Token you get from login>

{
    "oldEmail": "",
    "newEmail": ""
}

###

DELETE http://localhost:3000/api/user/<idOfUserToDelete>
Authorization: Bearer <Token you get from login>
